### ISSUE TITLE
[BUG] Edit Types 5e

### ISSUE THREAD

**Issue by Crowguard** [ironmonk88/monks-bloodsplats#34]
Errors & fails to open this settings window.

Uploading Foundry_Virtual_Tabletop_dPuSgalkL7.mp4…

Foundry 11.315
Bloodsplats 11.12
D&D 5e 3.0.0

**Comment by BillPitcher** [comment]
Confirmed: while check to install the D&D update.

**Comment by pesky-wobbit** [comment]
Same here. Here is the console:

foundry.js:753 TypeError: An error occurred while rendering EditTypes 199. key.split is not a function or its return value is not iterable
    at Object.getProperty (commons.js:2536:24)
    at Localization.localize (foundry.js:7586:27)
    at EditTypes.getData (edit-types.js:37:38)
    at EditTypes._render (foundry.js:5812:29)
    at EditTypes._render (foundry.js:6532:17)
    at EditTypes.render (foundry.js:5769:10)
    at SettingsConfig.onClickSubmenuWrapper (colorSetting.js:21:24)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)
    at 🎁SettingsConfig.prototype._onClickSubmenu#0 (libWrapper-wrapper.js:189:20)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
